trigger:
- dev

pool:
  name:  self_hosted 

stages:
- stage: LintAndUnitTest
  jobs:
  - job: LintAndUnitTest
    displayName: 'Lint and Unit Test'
    steps:
    - task: Gradle@3
      inputs:
        gradleWrapperFile: 'gradlew'
        tasks: 'test'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        sonarQubeRunAnalysis: false
        checkStyleRunAnalysis: true
        spotBugsAnalysis: false
    
    - script: |
        echo "Building and packaging the application with Gradle"
        gradle clean build
        cp build/libs/*.jar $(Build.ArtifactStagingDirectory)/
      displayName: 'Build and Archive Artifacts'

- stage: SonarQubeAnalysis
  displayName: 'SonarQube Analysis'
  jobs:
  - job: SonarQube
    steps:

    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '17'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'LocalDirectory'
        jdkFile: '/home/wayne/Downloads/jdk-17_linux-x64_bin.tar.gz'
        jdkDestinationDirectory: '/home/wayne/Downloads/Dest'
        cleanDestinationDirectory: true

    - task: SonarQubePrepare@4
      inputs:
        SonarQube: 'AzurePipeline'
        scannerMode: 'Other'
        extraProperties: |
          sonar.java.binaries=$(Build.SourcesDirectory)/build/classes/java/main
          sonar.host.url=http://localhost:9000  # Use 'localhost' here
    - script: |
        chmod +x ./gradlew
        ./gradlew test  # Run unit tests again (optional but recommended).
    - task: SonarQubeAnalyze@5
      inputs:
        jdkversion: 'JAVA_HOME'
    - task: SonarQubePublish@4
      inputs:
        pollingTimeoutSec: '300'

- stage: BuildImage
  jobs:
  - job: BuildDockerImage
    displayName: 'Build Docker Image'
    steps:
    - script: |
        # Clone the GitHub repository containing your Dockerfile
        git clone https://github.com/your-username/your-repo.git cloned-repo

        # Navigate to the cloned repository directory
        cd cloned-repo

        # Build the Docker image
        docker build -t zeinsss/test:02 .

        # Log in to Docker Hub or your container registry
        docker login -u $(DOCKERHUB_USERNAME) -p $(DOCKERHUB_PASSWORD)

        # Push the Docker image to the registry
        docker push zeinsss/test:02

        # Log out of Docker
        docker logout
      displayName: 'Build and Push Docker Image'

- stage: PullImage
  jobs:
  - job: PullDockerImage
    displayName: 'Pull Docker Image'
    steps:
    - script: |
        docker login -u $(DOCKERHUB_USERNAME) -p $(DOCKERHUB_PASSWORD)
        docker pull zeinsss/test:02
        docker logout
      displayName: 'Pull Docker Image'