trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: LintAndUnitTest
  jobs:
  - job: LintAndUnitTest
    displayName: 'Lint and Unit Test'
    steps:
    - script: 'echo "Starting Linting"'
      displayName: 'Starting Linting'

    - script: 'chmod +x ./gradlew'
      displayName: 'Grant Execute Permission'

    - script: './gradlew lint'
      displayName: 'Run Linting'

    - script: 'echo "Linting Completed"'
      displayName: 'Linting Completed'

    - script: 'echo "Starting Unit Testing"'
      displayName: 'Starting Unit Testing'

    - script: './gradlew test'
      displayName: 'Run Unit Tests'

    - script: 'echo "Unit Testing Completed"'
      displayName: 'Unit Testing Completed'
 # Add Java Tool Installer task to set JDK version, architecture, and source
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '17'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
    - task: SonarQubePrepare@5
      inputs:
        SonarQube: 'AzureSpringBootPipeline2'
        scannerMode: 'Other'
    - task: SonarQubePrepare@4
      inputs:
        SonarQube: 'AzureSpringBootPipeline'
        scannerMode: 'Other'
        configMode: 'manual'
        cliProjectKey: 'AzureSpringBootPipeline'
        cliProjectName: 'AzureSpringBootPipeline'
        extraProperties: |
          sonar.coverage.exclusions=**/generated/**,**/build/**,**/node_modules/**
          # Add any additional SonarQube analysis properties here

    # Add any other steps as needed
