apiVersion : apps/v1
kind: Deployment
metadata:
  name: springboot 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot 
    spec:
      containers:
      - name: springbootapp
        image: zeinsss/springbootapp:v1
        ports:
        - containerPort: 8080
        readinessProbe: # Readiness Probe
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe: # Liveness Probe
          httpGet:
            path: /live
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10