apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  selector:
    app: springboot # Label selector for your Spring Boot application pods
  ports:
    - name: http
      protocol: TCP
      port: 8080 # Port where your Spring Boot application is running
      targetPort: 8080 # Port your application listens on